### ISSUE TITLE
FileNotFoundError on train_loop()

### ISSUE THREAD

**Issue by ahkarimi** [Makbari1997/VAE-KPCA-HDBSCAN#2]
## Current Behavior
In the training of the VAE model, I encountered an error on line 112 that prevented me from loading the model's weights.

https://github.com/Makbari1997/VAE-KPCA-HDBSCAN/blob/7ce718c6a30416bc1cd06fc9c4a437dffed803ab/main.py#L112

Last commit is:
7ce718c6a30416bc1cd06fc9c4a437dffed803ab

The error message is:
```
Traceback (most recent call last):
  File "/content/drive/MyDrive/masoud/vae/main.py", line 135, in <module>
    run(config)
  File "/content/drive/MyDrive/masoud/vae/main.py", line 102, in run
    train_loop(
  File "/content/drive/MyDrive/masoud/vae/model/train.py", line 50, in train_loop
    model.save_weights(filepath=path, overwrite=True, save_format='h5')
  File "/usr/local/lib/python3.10/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/h5py/_hl/files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/usr/local/lib/python3.10/dist-packages/h5py/_hl/files.py", line 237, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 126, in h5py.h5f.create
FileNotFoundError: [Errno 2] Unable to create file (unable to open file: name = 'artifacts/persian_atis/vae/vae.h5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)
```

## Context (Environment)
My config is:
```
{
    "dataset" : "persian_atis",
    "seq_length" : "max",
    "finetune" : true,
    "finetune_epochs" : 60,
    "train_epochs" : 350,
    "batch_size" : 16,
    "vae_learning_rate" : 0.00002,
    "bert_freeze_layers" : 11,
    "bert" : "bert-base-multilingual-uncased",
    "activation" : "tanh",
    "vector_dim" : 768,
    "latent_dim" : 36,
    "encoder" : [512, 256, 128, 64],
    "decoder" : [64, 128, 256, 512, 768],
    "ood_threshold" : 0.2
}
```
and I am running the code on Google Colab.

**Comment by Makbari1997** [comment]
Dear Amir,
Thanks for your contribution!
The problem was with creating non-existed directories! The problem is solved now.
